### ISSUE TITLE
Crash when find_command() is called

### ISSUE THREAD

**Issue by jlaney** [vegitron/django-handlebars-i18n#4]
Traceback (most recent call last):

  File "/data/gradepage/builds/70/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)

  File "/data/gradepage/builds/70/src/django-handlebars-i18n/handlebars_i18n/views.py", line 345, in javascript_catalog
    catalog, plural = get_javascript_catalog(locale, domain, packages)

  File "/data/gradepage/builds/70/src/django-handlebars-i18n/handlebars_i18n/views.py", line 252, in get_javascript_catalog
    compile_messages(domain, path, default_locale)

  File "/data/gradepage/builds/70/src/django-handlebars-i18n/handlebars_i18n/monkey_patch.py", line 93, in compile_messages
    compile_message_file(file_path)

  File "/data/gradepage/builds/70/src/django-handlebars-i18n/handlebars_i18n/monkey_patch.py", line 99, in compile_message_file
    if find_command(program) is None:

  File "/data/gradepage/builds/70/lib/python2.6/site-packages/django/core/management/utils.py", line 59, in find_command
    path = os.environ.get('PATH', []).split(os.pathsep)

AttributeError: 'list' object has no attribute 'split'

**Comment by vegitron** [comment]
This is a Django bug: https://github.com/django/django/pull/2422

Set a path variable in the meantime.
